#pragma once

// I18N-01: catalog lint (pure; exercised by tests/test_i18n01_catalog.cpp). The
// reference key set is the English literals wrapped in tr("...") / trc("ctx",
// "text") in the C++ sources, so it is generated by scanning, never hand-kept.

#include "i18n/i18n.h"

#include <set>
#include <string>
#include <string_view>
#include <vector>

namespace i18n::lint {

/// Terms that must appear verbatim in a translation whose key contains them.
const std::vector<std::string> &doNotTranslate();

/// Keys of the tr("...") / trc("ctx","text") calls in `source` (trc yields
/// "ctx|text"). C string escapes and adjacent literal concatenation are handled.
std::set<std::string> extractKeys(std::string_view source);

/// Sorted placeholders of `s`: printf (%s %d %1$s %.2f, `%%` ignored) and
/// brace ({n}, {name}). Compared as multisets, so order may differ.
std::vector<std::string> placeholders(std::string_view s);

/// Problems of `catalog` against `referenceKeys`; empty means clean:
///  - orphan key (not in the reference set)
///  - placeholder multiset differs between key and non-empty translation
///  - a do-not-translate term in the key is missing from the translation
std::vector<std::string> check(const Catalog &catalog, const std::set<std::string> &referenceKeys);

/// I18N-02 coverage: one "missing translation: <key>" per reference key that
/// has no entry, or only an empty one (= untranslated), in `catalog`.
std::vector<std::string> checkCoverage(const Catalog &catalog, const std::set<std::string> &referenceKeys);

}  // namespace i18n::lint
